import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    alignContent: 'center',
    justifyContent: 'center',
  },
  wrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gestureDetectorWrap: {
    width: '100%',
    height: '100%',
    alignContent: 'center',
    justifyContent: 'center',
  },
  containerOverlay: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  maskContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  mask: {
    backgroundColor: 'red',
    borderRadius: 16,
  },
  coverHorizontal: {
    width: '100%',
    height: 'auto',
  },
  coverVertical: {
    width: 'auto',
    height: '100%',
  },
  mediaContainer: {
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    height: '100%',
  },
  leftShadow: {
    position: 'absolute',
    left: '-100%',
    width: '100%',
    top: -1,
    bottom: 0,
    backgroundColor: '#000000',
    opacity: 0.6,
    zIndex: 0,
    overflow: 'hidden',
  },
  bottomShadow: {
    position: 'absolute',
    top: '100%',
    width: '100%',
    height: '100%',
    left: 0,
    opacity: 0.6,
    backgroundColor: '#000000',
  },
  topShadow: {
    position: 'absolute',
    top: '-100%',
    width: '100%',
    height: '100%',
    left: 0,
    opacity: 0.6,
    backgroundColor: '#000000',
  },
  rightShadow: {
    position: 'absolute',
    right: '-100%',
    width: '100%',
    top: -1,
    bottom: 0,
    opacity: 0.6,
    backgroundColor: '#000000',
  },
  leftBottomBorderShadowContainer: {
    position: 'absolute',
    bottom: -3,
    left: -10,
    overflow: 'visible',
    backgroundColor: '#000000',
    zIndex: 0,
  },
  leftBottomBorderShadow: {
    position: 'absolute',
  },

  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 60 / 5,
    borderBottomWidth: 60 / 5,
    borderLeftWidth: 60 / 5,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',

    borderBottomColor: '#ffffff50',
    borderLeftColor: 'transparent',
  },
});
